#source common.sh
#app_name=mongodb
#
#print_heading "Copy MongoDB repo file"
#cp mongodb.repo /etc/yum.repos.d/mongodb.repo &>>$log_file
#status_check $?
#
#print_heading "Install MongoDB Server"
#dnf install mongodb-org -y &>>$log_file
#status_check $?
#
#print_heading "Update MongoDB listen address"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>$log_file
#status_check $?
#
#print_heading "Start MongoDB service"
#systemctl enable mongod &>>$log_file
#systemctl restart mongod &>>$log_file
#status_check $?
- name: Set a hostname
  ansible.builtin.hostname:
    name: mongodb
    
- name: Copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Server"
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Replace Monfodb listen address in conf file 
  ansible.builtin.replace:
    path: /etc/mongod.conf 
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start mongodb service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted 
    enabled: yes

- name: Enable service mongodb and not touch the state
  ansible.builtin.service:
    name: mongod
    enabled: yes    