- name: set prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: load maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: load swl file
  ansible.builtin.shell: mysql -h mysql-{{ env }}.devopspractice.info -uroot -pRoboshop@1 < /app/db/{{ item }}.sql
  loop: 
    - schema
    - app-user
    - master-data       

- name: Restart Shipping
  ansible.builtin.systemd_service:
    name: shipping     
    state: restarted
    enabled: yes