#Install Nginx
dnf makecache
dnf module disable nginx -y
dnf module enable nginx:1.24 -y
dnf install nginx -y
cp -r nginx.conf /etc/nginx/nginx.conf
#Start & Enable Nginx service
systemctl enable nginx
systemctl start nginx
rm -rf /usr/share/nginx/html/*
#Download the frontend content
curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#Extract the frontend content.
cd /usr/share/nginx/html
unzip /tmp/frontend.zip
systemctl restart nginx ; tail -f /var/log/messages


- name: Install Cache on server
  ansible.builtin.dnf:
    name: cache
    state: latest

- name: module disable nginx -y
  ansible.builtin.dnf:
    name: nginx
    state: absent

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: cp -r nginx.conf /etc/nginx/nginx.conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
   
- name: systemctl start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Download frontend.zip
  ansible.builtin.get_url:
    url: curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/
   
- name: unzip /tmp/frontend.zip
  ansible.builtin.unarchive:
    src: /tmp/
    dest: /usr/share/nginx/html


- name: systemctl restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes