#- name: set prompt
#  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}
#
#- name: Load Maven
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: maven
#
- name: Load NodeJS
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs