 - name: Make dnf cache
   ansible.builtin.shell: dnf makecache
   
 - name: module disable nginx -y
   ansible.builtin.shell: dnf module disable nginx -y
 
 - name: module enable nginx -y
   ansible.builtin.shell: dnf module enable nginx:1.24 -y  
 
 - name: Install Nginx
   ansible.builtin.shell: dnf install nginx -y
 - name: Remove file (delete file)
   ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent  
 
 - name: copy nginx file
   ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
 - name: Start Nginx service
   ansible.builtin.shell: systemctl start nginx
# - name: Create application directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory
#
# - name: Download and extract application content
#   ansible.builtin.unarchive: 
#     src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#     dest: /usr/share/nginx/html/
#     remote_src: yes
  
# - name: Restart nginx servfice
#   ansible.builtin.shell: systemctl restart nginx
#     #name: nginx
#     #state: restarted
#     #enabled: yes  