#source common.sh
#app_name=mysql
#
#if [ -z "$1" ]; then
#  echo INput MySQL Root Password is missing
#  exit 1
#fi
#
#MYSQL_ROOT_PASSWORD=$1
#
#print_heading "Install MySQL Server"
#dnf install mysql-server -y &>>$log_file
#status_check $?
#
#print_heading "Start MySQL Service"
#systemctl enable mysqld &>>$log_file
#systemctl start mysqld &>>$log_file
#status_check $?
#
#print_heading "Setup MySQL Password"
#mysql_secure_installation --set-root-pass $MYSQL_ROOT_PASSWORD &>>$log_file
#status_check $?

- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: dnf make cache
  ansible.builtin.shell: dnf makecache

- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start mysql-server service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: setup mysql Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass Roboshop@1      



