#nodejs_setup
#
#print_heading "Copy MongoDB repo file"
#cp $scripts_path/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>$log_file
#status_check $?
#
#print_heading "Install MongoDB Client"
#dnf install mongodb-mongosh -y &>>$log_file
#status_check $?
#
#print_heading "Load Master Data"
#mongosh --host mongodb.devopspractice.info </app/db/master-data.js  &>>$log_file
#status_check $?
#
#print_heading "Restart Catalogue Service"
#systemctl restart catalogue &>>$log_file
#status_check $?
#
#
- name: Set prnt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}  
