#go for app pre requesites

#- name: Add Application User
#  ansible.builtin.user:
#    name: roboshop
#
#- name: Delete old app directory
#  ansible.builtin.file:
#    path: /app
#    state: absent
#
#- name: Create App directory
#  ansible.builtin.file:
#    path: /app
#    state: directory
#
#- name: Download and extract application content
#  ansible.builtin.unarchive: 
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
#    dest: /app
#    remote_src: yes 

#- name: Adding Application User
#  ansible.builtin.u#ser:
#    name: roboshop#
#
#- name: Remove old #content
#  ansible.builtin.f#ile:
#    path: "{{ app_p#ath }}"
#    state: absent#
#
#- name: Create App #Directory
#  ansible.builtin.f#ile:
#    path: "{{ app_p#ath }}"
#    state: director#y
#
#- name: Download & #Extract Application Content
#  ansible.builtin.u#narchive:
#    src: https://ro#boshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
#    dest: "{{ app_p#ath}}"
#    remote_src: yes#
#
- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete old Application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes