#source common.sh
#app_name=catalogue
#
#nodejs_setup
#
#print_heading "Copy MongoDB repo file"
#cp $scripts_path/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>$log_file
#status_check $?
#
#print_heading "Install MongoDB Client"
#dnf install mongodb-mongosh -y &>>$log_file
#status_check $?
#
#print_heading "Load Master Data"
#mongosh --host mongodb.devopspractice.info </app/db/master-data.js  &>>$log_file
#status_check $?
#
#print_heading "Restart Catalogue Service"
#systemctl restart catalogue &>>$log_file
#status_check $?

- name: Disable Default nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs 20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install Nodejs
  ansible.builtin.dnf: 
    name: nodejs
    state: installed

- name: Include App Prequestes
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml


- name: Install NodeJS Dependencies
  community.general.npm:
    path: /app

- name: Systemd Setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml
