- name: Install Python
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - python3
    - gcc
    - python-devel

- name: Load app prereqiuities
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml

- name: Install Python Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:  
    chdir: /app

- name: Systemd setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml 

